# Generated by Django 3.0.3 on 2020-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websites', '0002_auto_20200525_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Image_url',
        ),
        migrations.AddField(
            model_name='slider',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='Countries',
            field=models.ManyToManyField(blank=True, to='Websites.Countries'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='Websites.Sub_Categories'),
        ),
    ]
