# Generated by Django 3.0.3 on 2020-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websites', '0003_auto_20200527_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Info',
            field=models.CharField(default='Welcome to links2web', max_length=250),
            preserve_default=False,
        ),
    ]
