# Generated by Django 3.1.2 on 2020-11-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Websites', '0004_auto_20200527_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='Countries',
            field=models.ManyToManyField(blank=True, null=True, to='Websites.Countries'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='Tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tags', to='Websites.Sub_Categories'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='Websites.categories'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='websites',
            name='website',
            field=models.CharField(max_length=250),
        ),
    ]
