# Generated by Django 3.1.2 on 2020-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websites', '0005_auto_20201108_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='Countries',
            field=models.ManyToManyField(blank=True, to='Websites.Countries'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='Websites.Sub_Categories'),
        ),
    ]
