# Generated by Django 3.1.2 on 2020-11-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Websites', '0006_auto_20201108_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Image',
        ),
    ]
